server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: employee
          uri: lb://employee
          predicates:
            - Path=/employee/**
        - id: timesheet
          uri: lb://timesheet
          predicates:
            - Path=/timesheet/**
        - id: profile
          uri: lb://profile
          predicates:
            - Path=/profile/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
